version: '2'
services:
        main:
                build:
                        context: .
                        dockerfile: main.Dockerfile
                user: "${DOCKER_USER_UID}:${DOCKER_USER_GID}"
                volumes:
                        - ./:/var/www
                        - ./docker/log/apache/main:/var/log/apache2/
                networks:
                        - urler
                working_dir: /var/www
                environment:
                        VIRTUAL_HOST: ${DOCKER_MAIN_DOMAIN}
                        PHP_DEBUGGER: xdebug
                        XDEBUG_REMOTE_HOST: 172.17.0.1
                        XDEBUG_REMOTE_CONNECT_BACK: 0
                        XDEBUG_REMOTE_PORT: 9000
                        WEB_DOCUMENT_ROOT: /var/www/web
                        XDEBUG_REMOTE_AUTOSTART: 1
                restart: always

        urlersql:
                image: "mariadb"
                volumes:
                        - urlerdb:/var/lib/mysql
                environment:
                        MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
                        MYSQL_DATABASE: ${MYSQL_DATABASE}
                        MYSQL_USER: ${MYSQL_USER}
                        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
                ports:
                        - "${DOCKER_MYSQL_PORT}:3306"
                networks:
                        - urler
                restart: always

        nginx-proxy:
                image: jwilder/nginx-proxy:alpine
                ports:
                        - "${DOCKER_HTTP_PORT}:80"
                        - "${DOCKER_SSL_PORT}:443"
                        - "${DOCKER_DEBUG_PORT}:9000"
                networks:
                        - urler
                environment:
                        DEFAULT_HOST: ${DOCKER_MAIN_DOMAIN} #default host
                        CERT_NAME: mycertificate # Wildcard Certificate name without extension
                volumes:
                        - /var/run/docker.sock:/tmp/docker.sock:ro
                        - ./docker/certs:/etc/nginx/certs  #certificate path in docker container

                restart: always
                privileged: true
networks:
        urler:

volumes:
        urlerdb:
                driver: "local"
